const mongoose = require("mongoose")
const MONGO_URI = "mongodb+srv://testApp:sr0d1GR4SmKPXJvZ@cluster0.x9a7koe.mongodb.net/testNft?retryWrites=true&w=majority"
const Word = require("./wordModel")

const main = async () => {
    console.log("Starting.....")
    const words= [
        "six",
        "text",
        "round",
        "decide",
        "fix",
        "sponsor",
        "amazing",
        "vocal",
        "bring",
        "proud",
        "defense",
        "wave",
        "play",
        "run",
        "life",
        "rule",
        "churn",
        "major",
        "injury",
        "educate",
        "popular",
        "crime",
        "spike",
        "host",
        "box",
        "hunt",
        "outer",
        "visit",
        "suffer",
        "sell",
        "guide",
        "pluck",
        "claw",
        "canyon",
        "trial",
        "olympic",
        "base",
        "moment",
        "payment",
        "atom",
        "daughter",
        "radio",
        "blind",
        "light",
        "own",
        "cute",
        "dizzy",
        "kitten",
        "large",
        "pumpkin",
        "erode",
        "ladder",
        "future",
        "solid",
        "ready",
        "inspire",
        "cement",
        "release",
        "wrestle",
        "rose",
        "room",
        "chase",
        "absorb",
        "govern",
        "deer",
        "item",
        "peasant",
        "gown",
        "century",
        "orient",
        "gun",
        "abandon",
        "fresh",
        "wheat",
        "appear",
        "inflict",
        "hard",
        "beauty",
        "unlock",
        "chair",
        "project",
        "gate",
        "still",
        "stadium",
        "useful",
        "initial",
        "rally",
        "left",
        "west",
        "strategy",
        "robust",
        "code",
        "hover",
        "layer",
        "expand",
        "clerk",
        "demand",
        "best",
        "buyer",
        "easy",
        "polar",
        "comic",
        "exile",
        "market",
        "kingdom",
        "memory",
        "bean",
        "two",
        "laugh",
        "addict",
        "element",
        "nasty",
        "slight",
        "phrase",
        "dial",
        "push",
        "vast",
        "link",
        "rail",
        "source",
        "mutual",
        "busy",
        "noble",
        "card",
        "earth",
        "arrow",
        "ride",
        "fade",
        "calm",
        "neglect",
        "ridge",
        "baby",
        "bread",
        "love",
        "exhaust",
        "order",
    ]
    
    const arr = words.map(word => ({
        word,
        taken: Array(word.length).fill(false)
    }))

    const res = await Word.insertMany(arr)
    console.log(res)
    process.exit(0)
}

mongoose.set('strictQuery', true);
mongoose
    .connect(MONGO_URI, {
        useNewUrlParser: true,
        useUnifiedTopology: true,
    })
    .then(main)
    .catch(err => console.log(err))